### ISSUE TITLE
Return success or error when adding a track with addTrack()

### ISSUE THREAD

**Issue by BERNARDO31P** [regosen/Gapless-5#25]
Greetings,

I was wondering if it's possible to return a boolean (or object with the full error) when adding a track was successful or not. I'm adding tracks with the `addTrack()` function. 

Kind regards,
Bernardo

**Comment by BERNARDO31P** [comment]
To be more percise: I need to catch network errors, for example, 500 and 502 from the `fetch` function inside the Gapless-5 library.

**Comment by regosen** [comment]
addTrack wouldn't be able to return a boolean with that information because it only adds the track to a loading queue.  That being said, you can use the `onerror` callback, which will be called with the same audio path you used in addTrack.

Something like this:
```
    gapless.onerror = (audioPath) => {
      console.log(`Failed to load: ${audioPath}`);
    };
    gapless.addTrack('my_sound.flac');
    // if the fetch fails, you should see "Failed to load: my_sound.flac" in the console
 ```

**Comment by BERNARDO31P** [comment]
I didn't realize that there is an `onerror` callback. 

I tried using it, but it didn't catch the net::ERR_FAILED nor the net::ERR_INTERNET_DISCONNECTED error when there's no internet connection.

**Comment by regosen** [comment]
Thanks for catching that, indeed `onerror` wasn't triggering in those cases.  I just pushed a new version of Gapless 5 (v1.3.2) that should fix this.

**Comment by BERNARDO31P** [comment]
I think not all errors are caught. When I turn off the internet the player crashes and doesn't accept any commands anymore.
Here's the console log: "net::ERR_INTERNET_DISCONNECTED"

It should ignore the error, call the onError callback and then accept a new "addTrack()" request.

**Comment by regosen** [comment]
Are you hosting the player locally when testing with the disconnected network?  I just confirmed I get an onerror callback when I disconnect from the network (but that's if I'm hosting the player locally and accessing audio remotely).

If you disconnect the network AND are running the player remotely, well I don't think I can help much there.  Even GitHub stops accepting commands when I disconnect from the network.

**Comment by BERNARDO31P** [comment]
I'm not testing it on a local network. 

Why shouldn't it be possible? Imagine this scenario: 

```
// Has internet
let gapless = new Gapless({});

gapless.addTrack("track1.mp3");

gapless.onplay = () => {
    // Lost internet connection 
    addTrack("track2.mp3");
}

gapless.onerror = () => {
    // Has internet again
    addTrack("track2.mp3");
}

gapless.play();
```

Isn't this possible? I want to archive a YouTube-like experience.

**Comment by regosen** [comment]
Ok, I just pushed some improvements to error handling and tested by disconnecting my network while loading tracks, seems to work as expected.  Try 1.3.5 if you have time!

**Comment by BERNARDO31P** [comment]
It's almost working I guess. The only problem is that when a track can't download the ID should not update like here:

```
1. Setting track number to 2
2. gapless5.js:155 Stopping: https://beta.bernardo.fm/system/song/45/5
3. gapless5.js:198 Playing WebAudio: https://beta.bernardo.fm/system/song/45/10
4. gapless5.js:182 onEnded will be called in 5.00 sec
5. gapless5.js:609 Loading track 3: https://beta.bernardo.fm/system/song/45/15
6. gapless5.js:110 Failed to load audio track
7. gapless5.js:155 Stopping: https://beta.bernardo.fm/system/song/45/15
8. gapless5.js:359 GET https://beta.bernardo.fm/system/song/45/15 
9. gapless5.js:155 Stopping: https://beta.bernardo.fm/system/song/45/15
10. gapless5.js:182 onEnded will be called in 5.00 sec
11. gapless5.js:441 Setting track number to 3
12. gapless5.js:155 Stopping: https://beta.bernardo.fm/system/song/45/10
13. gapless5.js:609 Loading track 4: https://beta.bernardo.fm/system/song/45/15
```

Part 3 became part 4 which breaks my system, take a look at lines 5 and 13. It should get removed.

**Comment by BERNARDO31P** [comment]
I could fix it myself by using `removeTrack()` problem is solved.

**Comment by BERNARDO31P** [comment]
Sorry, it's not fixed yet. I noticed that somehow the gapless player starts to loop when losing the connection. It tries to call the onEnded callback every 5 seconds, even when the part length changes. 

Console.log:

```
Loading track 2: https://beta.bernardo.fm/system/song/43/10
gapless5.js:182 onEnded will be called in 5.00 sec
gapless5.js:441 Setting track number to 2
gapless5.js:155 Stopping: https://beta.bernardo.fm/system/song/43/5
gapless5.js:198 Playing WebAudio: https://beta.bernardo.fm/system/song/43/10
gapless5.js:182 onEnded will be called in 5.00 sec                                                                 // Only a single onEnded
gapless5.js:609 Loading track 3: https://beta.bernardo.fm/system/song/43/15
gapless5.js:110 Failed to load audio track
onError @ gapless5.js:110
request.onerror @ gapless5.js:356
error (async)
Gapless5Source.load @ gapless5.js:354
Gapless5FileList.updateLoading @ gapless5.js:610
Gapless5FileList.add @ gapless5.js:634
Gapless5.addTrack @ gapless5.js:928
downloadPart @ music.js:635
(anonymous) @ music.js:602
setInterval (async)
prepareNextPart @ music.js:583
(anonymous) @ music.js:476
setTimeout (async)
player.onplay @ music.js:475
playAudioFile @ gapless5.js:207
Gapless5Source.play @ gapless5.js:248
Gapless5FileList.gotoTrack @ gapless5.js:458
Gapless5.gotoTrack @ gapless5.js:1032
Gapless5.onEndedCallback @ gapless5.js:893
onEnded @ gapless5.js:91
setTimeout (async)
setEndedCallbackTime @ gapless5.js:183
playAudioFile @ gapless5.js:209
Gapless5Source.play @ gapless5.js:248
Gapless5FileList.gotoTrack @ gapless5.js:458
Gapless5.gotoTrack @ gapless5.js:1032
Gapless5.onEndedCallback @ gapless5.js:893
onEnded @ gapless5.js:91
setTimeout (async)
setEndedCallbackTime @ gapless5.js:183
playAudioFile @ gapless5.js:209
onLoadedWebAudio @ gapless5.js:124
(anonymous) @ gapless5.js:327
Promise.then (async)
onLoadWebAudio @ gapless5.js:325
request.onload @ gapless5.js:351
load (async)
Gapless5Source.load @ gapless5.js:349
Gapless5FileList.updateLoading @ gapless5.js:610
Gapless5FileList.add @ gapless5.js:634
Gapless5.addTrack @ gapless5.js:928
downloadPart @ music.js:635
(anonymous) @ music.js:105
(anonymous) @ tools.js:71
(anonymous) @ tools.js:63
gapless5.js:155 Stopping: https://beta.bernardo.fm/system/song/43/15
gapless5.js:359 GET https://beta.bernardo.fm/system/song/43/15 net::ERR_INTERNET_DISCONNECTED
Gapless5Source.load @ gapless5.js:359
Gapless5FileList.updateLoading @ gapless5.js:610
Gapless5FileList.add @ gapless5.js:634
Gapless5.addTrack @ gapless5.js:928
downloadPart @ music.js:635
(anonymous) @ music.js:602
setInterval (async)
prepareNextPart @ music.js:583
(anonymous) @ music.js:476
setTimeout (async)
player.onplay @ music.js:475
playAudioFile @ gapless5.js:207
Gapless5Source.play @ gapless5.js:248
Gapless5FileList.gotoTrack @ gapless5.js:458
Gapless5.gotoTrack @ gapless5.js:1032
Gapless5.onEndedCallback @ gapless5.js:893
onEnded @ gapless5.js:91
setTimeout (async)
setEndedCallbackTime @ gapless5.js:183
playAudioFile @ gapless5.js:209
Gapless5Source.play @ gapless5.js:248
Gapless5FileList.gotoTrack @ gapless5.js:458
Gapless5.gotoTrack @ gapless5.js:1032
Gapless5.onEndedCallback @ gapless5.js:893
onEnded @ gapless5.js:91
setTimeout (async)
setEndedCallbackTime @ gapless5.js:183
playAudioFile @ gapless5.js:209
onLoadedWebAudio @ gapless5.js:124
(anonymous) @ gapless5.js:327
Promise.then (async)
onLoadWebAudio @ gapless5.js:325
request.onload @ gapless5.js:351
load (async)
Gapless5Source.load @ gapless5.js:349
Gapless5FileList.updateLoading @ gapless5.js:610
Gapless5FileList.add @ gapless5.js:634
Gapless5.addTrack @ gapless5.js:928
downloadPart @ music.js:635
(anonymous) @ music.js:105
(anonymous) @ tools.js:71
(anonymous) @ tools.js:63
/system/song/43/15:1 GET https://beta.bernardo.fm/system/song/43/15 net::ERR_INTERNET_DISCONNECTED
gapless5.js:110 MEDIA_ELEMENT_ERROR: Format error
onError @ gapless5.js:110
error (async)
getHtml5Audio @ gapless5.js:371
Gapless5Source.load @ gapless5.js:383
Gapless5FileList.updateLoading @ gapless5.js:610
Gapless5FileList.add @ gapless5.js:634
Gapless5.addTrack @ gapless5.js:928
downloadPart @ music.js:635
(anonymous) @ music.js:602
setInterval (async)
prepareNextPart @ music.js:583
(anonymous) @ music.js:476
setTimeout (async)
player.onplay @ music.js:475
playAudioFile @ gapless5.js:207
Gapless5Source.play @ gapless5.js:248
Gapless5FileList.gotoTrack @ gapless5.js:458
Gapless5.gotoTrack @ gapless5.js:1032
Gapless5.onEndedCallback @ gapless5.js:893
onEnded @ gapless5.js:91
setTimeout (async)
setEndedCallbackTime @ gapless5.js:183
playAudioFile @ gapless5.js:209
Gapless5Source.play @ gapless5.js:248
Gapless5FileList.gotoTrack @ gapless5.js:458
Gapless5.gotoTrack @ gapless5.js:1032
Gapless5.onEndedCallback @ gapless5.js:893
onEnded @ gapless5.js:91
setTimeout (async)
setEndedCallbackTime @ gapless5.js:183
playAudioFile @ gapless5.js:209
onLoadedWebAudio @ gapless5.js:124
(anonymous) @ gapless5.js:327
Promise.then (async)
onLoadWebAudio @ gapless5.js:325
request.onload @ gapless5.js:351
load (async)
Gapless5Source.load @ gapless5.js:349
Gapless5FileList.updateLoading @ gapless5.js:610
Gapless5FileList.add @ gapless5.js:634
Gapless5.addTrack @ gapless5.js:928
downloadPart @ music.js:635
(anonymous) @ music.js:105
(anonymous) @ tools.js:71
(anonymous) @ tools.js:63
gapless5.js:155 Stopping: https://beta.bernardo.fm/system/song/43/15
gapless5.js:647 Decrementing track number to 1
gapless5.js:609 Loading track 3: https://beta.bernardo.fm/system/song/43/15
gapless5.js:110 Failed to load audio track
onError @ gapless5.js:110
request.onerror @ gapless5.js:356
error (async)
Gapless5Source.load @ gapless5.js:354
Gapless5FileList.updateLoading @ gapless5.js:610
Gapless5FileList.add @ gapless5.js:634
Gapless5.addTrack @ gapless5.js:928
downloadPart @ music.js:635
(anonymous) @ music.js:602
setInterval (async)
prepareNextPart @ music.js:583
(anonymous) @ music.js:464
setTimeout (async)
player.onerror @ music.js:460
onError @ gapless5.js:111
error (async)
getHtml5Audio @ gapless5.js:371
Gapless5Source.load @ gapless5.js:383
Gapless5FileList.updateLoading @ gapless5.js:610
Gapless5FileList.add @ gapless5.js:634
Gapless5.addTrack @ gapless5.js:928
downloadPart @ music.js:635
(anonymous) @ music.js:602
setInterval (async)
prepareNextPart @ music.js:583
(anonymous) @ music.js:476
setTimeout (async)
player.onplay @ music.js:475
playAudioFile @ gapless5.js:207
Gapless5Source.play @ gapless5.js:248
Gapless5FileList.gotoTrack @ gapless5.js:458
Gapless5.gotoTrack @ gapless5.js:1032
Gapless5.onEndedCallback @ gapless5.js:893
onEnded @ gapless5.js:91
setTimeout (async)
setEndedCallbackTime @ gapless5.js:183
playAudioFile @ gapless5.js:209
Gapless5Source.play @ gapless5.js:248
Gapless5FileList.gotoTrack @ gapless5.js:458
Gapless5.gotoTrack @ gapless5.js:1032
Gapless5.onEndedCallback @ gapless5.js:893
onEnded @ gapless5.js:91
setTimeout (async)
setEndedCallbackTime @ gapless5.js:183
playAudioFile @ gapless5.js:209
onLoadedWebAudio @ gapless5.js:124
(anonymous) @ gapless5.js:327
Promise.then (async)
onLoadWebAudio @ gapless5.js:325
request.onload @ gapless5.js:351
load (async)
Gapless5Source.load @ gapless5.js:349
Gapless5FileList.updateLoading @ gapless5.js:610
Gapless5FileList.add @ gapless5.js:634
Gapless5.addTrack @ gapless5.js:928
downloadPart @ music.js:635
(anonymous) @ music.js:105
(anonymous) @ tools.js:71
(anonymous) @ tools.js:63
gapless5.js:155 Stopping: https://beta.bernardo.fm/system/song/43/15
gapless5.js:359 GET https://beta.bernardo.fm/system/song/43/15 net::ERR_INTERNET_DISCONNECTED
Gapless5Source.load @ gapless5.js:359
Gapless5FileList.updateLoading @ gapless5.js:610
Gapless5FileList.add @ gapless5.js:634
Gapless5.addTrack @ gapless5.js:928
downloadPart @ music.js:635
(anonymous) @ music.js:602
setInterval (async)
prepareNextPart @ music.js:583
(anonymous) @ music.js:464
setTimeout (async)
player.onerror @ music.js:460
onError @ gapless5.js:111
error (async)
getHtml5Audio @ gapless5.js:371
Gapless5Source.load @ gapless5.js:383
Gapless5FileList.updateLoading @ gapless5.js:610
Gapless5FileList.add @ gapless5.js:634
Gapless5.addTrack @ gapless5.js:928
downloadPart @ music.js:635
(anonymous) @ music.js:602
setInterval (async)
prepareNextPart @ music.js:583
(anonymous) @ music.js:476
setTimeout (async)
player.onplay @ music.js:475
playAudioFile @ gapless5.js:207
Gapless5Source.play @ gapless5.js:248
Gapless5FileList.gotoTrack @ gapless5.js:458
Gapless5.gotoTrack @ gapless5.js:1032
Gapless5.onEndedCallback @ gapless5.js:893
onEnded @ gapless5.js:91
setTimeout (async)
setEndedCallbackTime @ gapless5.js:183
playAudioFile @ gapless5.js:209
Gapless5Source.play @ gapless5.js:248
Gapless5FileList.gotoTrack @ gapless5.js:458
Gapless5.gotoTrack @ gapless5.js:1032
Gapless5.onEndedCallback @ gapless5.js:893
onEnded @ gapless5.js:91
setTimeout (async)
setEndedCallbackTime @ gapless5.js:183
playAudioFile @ gapless5.js:209
onLoadedWebAudio @ gapless5.js:124
(anonymous) @ gapless5.js:327
Promise.then (async)
onLoadWebAudio @ gapless5.js:325
request.onload @ gapless5.js:351
load (async)
Gapless5Source.load @ gapless5.js:349
Gapless5FileList.updateLoading @ gapless5.js:610
Gapless5FileList.add @ gapless5.js:634
Gapless5.addTrack @ gapless5.js:928
downloadPart @ music.js:635
(anonymous) @ music.js:105
(anonymous) @ tools.js:71
(anonymous) @ tools.js:63
/system/song/43/15:1 GET https://beta.bernardo.fm/system/song/43/15 net::ERR_INTERNET_DISCONNECTED
gapless5.js:110 MEDIA_ELEMENT_ERROR: Format error
onError @ gapless5.js:110
error (async)
getHtml5Audio @ gapless5.js:371
Gapless5Source.load @ gapless5.js:383
Gapless5FileList.updateLoading @ gapless5.js:610
Gapless5FileList.add @ gapless5.js:634
Gapless5.addTrack @ gapless5.js:928
downloadPart @ music.js:635
(anonymous) @ music.js:602
setInterval (async)
prepareNextPart @ music.js:583
(anonymous) @ music.js:464
setTimeout (async)
player.onerror @ music.js:460
onError @ gapless5.js:111
error (async)
getHtml5Audio @ gapless5.js:371
Gapless5Source.load @ gapless5.js:383
Gapless5FileList.updateLoading @ gapless5.js:610
Gapless5FileList.add @ gapless5.js:634
Gapless5.addTrack @ gapless5.js:928
downloadPart @ music.js:635
(anonymous) @ music.js:602
setInterval (async)
prepareNextPart @ music.js:583
(anonymous) @ music.js:476
setTimeout (async)
player.onplay @ music.js:475
playAudioFile @ gapless5.js:207
Gapless5Source.play @ gapless5.js:248
Gapless5FileList.gotoTrack @ gapless5.js:458
Gapless5.gotoTrack @ gapless5.js:1032
Gapless5.onEndedCallback @ gapless5.js:893
onEnded @ gapless5.js:91
setTimeout (async)
setEndedCallbackTime @ gapless5.js:183
playAudioFile @ gapless5.js:209
Gapless5Source.play @ gapless5.js:248
Gapless5FileList.gotoTrack @ gapless5.js:458
Gapless5.gotoTrack @ gapless5.js:1032
Gapless5.onEndedCallback @ gapless5.js:893
onEnded @ gapless5.js:91
setTimeout (async)
setEndedCallbackTime @ gapless5.js:183
playAudioFile @ gapless5.js:209
onLoadedWebAudio @ gapless5.js:124
(anonymous) @ gapless5.js:327
Promise.then (async)
onLoadWebAudio @ gapless5.js:325
request.onload @ gapless5.js:351
load (async)
Gapless5Source.load @ gapless5.js:349
Gapless5FileList.updateLoading @ gapless5.js:610
Gapless5FileList.add @ gapless5.js:634
Gapless5.addTrack @ gapless5.js:928
downloadPart @ music.js:635
(anonymous) @ music.js:105
(anonymous) @ tools.js:71
(anonymous) @ tools.js:63
gapless5.js:155 Stopping: https://beta.bernardo.fm/system/song/43/15
gapless5.js:647 Decrementing track number to 0
gapless5.js:609 Loading track 3: https://beta.bernardo.fm/system/song/43/15
gapless5.js:182 onEnded will be called in 5.00 sec
gapless5.js:441 Setting track number to 3
gapless5.js:155 Stopping: https://beta.bernardo.fm/system/song/43/0
gapless5.js:155 Stopping: https://beta.bernardo.fm/system/song/43/15
gapless5.js:198 Playing WebAudio: https://beta.bernardo.fm/system/song/43/15
gapless5.js:182 onEnded will be called in 5.00 sec                                                                 // Now there are two onEnded callback being called
gapless5.js:609 Loading track 4: https://beta.bernardo.fm/system/song/43/20
gapless5.js:182 onEnded will be called in 5.00 sec                                                                 // Here is the second
gapless5.js:441 Setting track number to 4
gapless5.js:155 Stopping: https://beta.bernardo.fm/system/song/43/15
gapless5.js:198 Playing WebAudio: https://beta.bernardo.fm/system/song/43/20
gapless5.js:182 onEnded will be called in 5.00 sec
gapless5.js:609 Loading track 5: https://beta.bernardo.fm/system/song/43/25
gapless5.js:182 onEnded will be called in 5.00 sec
gapless5.js:441 Setting track number to 5
gapless5.js:155 Stopping: https://beta.bernardo.fm/system/song/43/20
gapless5.js:198 Playing WebAudio: https://beta.bernardo.fm/system/song/43/25
gapless5.js:182 onEnded will be called in 5.00 sec
gapless5.js:609 Loading track 6: https://beta.bernardo.fm/system/song/43/30
gapless5.js:182 onEnded will be called in 5.00 sec
gapless5.js:441 Setting track number to 6
gapless5.js:155 Stopping: https://beta.bernardo.fm/system/song/43/25
gapless5.js:198 Playing WebAudio: https://beta.bernardo.fm/system/song/43/30
gapless5.js:182 onEnded will be called in 5.00 sec
gapless5.js:609 Loading track 7: https://beta.bernardo.fm/system/song/43/35
gapless5.js:182 onEnded will be called in 5.00 sec
gapless5.js:441 Setting track number to 7
gapless5.js:155 Stopping: https://beta.bernardo.fm/system/song/43/30
gapless5.js:198 Playing WebAudio: https://beta.bernardo.fm/system/song/43/35
gapless5.js:182 onEnded will be called in 5.00 sec
gapless5.js:609 Loading track 8: https://beta.bernardo.fm/system/song/43/40
gapless5.js:182 onEnded will be called in 5.00 sec
gapless5.js:441 Setting track number to 8
gapless5.js:155 Stopping: https://beta.bernardo.fm/system/song/43/35
gapless5.js:198 Playing WebAudio: https://beta.bernardo.fm/system/song/43/40
gapless5.js:182 onEnded will be called in 5.00 sec
gapless5.js:609 Loading track 9: https://beta.bernardo.fm/system/song/43/45
gapless5.js:182 onEnded will be called in 5.00 sec
gapless5.js:441 Setting track number to 9
gapless5.js:155 Stopping: https://beta.bernardo.fm/system/song/43/40
gapless5.js:198 Playing WebAudio: https://beta.bernardo.fm/system/song/43/45
gapless5.js:182 onEnded will be called in 5.00 sec
gapless5.js:609 Loading track 10: https://beta.bernardo.fm/system/song/43/50
gapless5.js:182 onEnded will be called in 5.00 sec
gapless5.js:441 Setting track number to 10
gapless5.js:155 Stopping: https://beta.bernardo.fm/system/song/43/45
gapless5.js:198 Playing WebAudio: https://beta.bernardo.fm/system/song/43/50
gapless5.js:182 onEnded will be called in 10.00 sec                                                          // Now the length changed
gapless5.js:609 Loading track 11: https://beta.bernardo.fm/system/song/43/60
gapless5.js:182 onEnded will be called in 5.00 sec                                                            // But onEnded will still call after 5 seconds
gapless5.js:441 Setting track number to 11
gapless5.js:155 Stopping: https://beta.bernardo.fm/system/song/43/50
gapless5.js:198 Playing WebAudio: https://beta.bernardo.fm/system/song/43/60
gapless5.js:182 onEnded will be called in 10.00 sec
gapless5.js:609 Loading track 12: https://beta.bernardo.fm/system/song/43/70
gapless5.js:155 Stopping: https://beta.bernardo.fm/system/song/43/60
gapless5.js:182 onEnded will be called in 5.00 sec
```

I hope you understand the problem. I don't how to explain it better. I've added some comments to clarify the problem.

**Comment by BERNARDO31P** [comment]
I also noticed something else, if there's an error within the playtime of a part then the queuing doesn't work. 

Example:
```
Playing part 1 which is 20 seconds (success)
Instantly trying to download part 2 (error)
Part 1 is now at 5 seconds
Retrying to download part 2 (success)
Queuing part 2
Part 1 ends
Player stops
```

I hope this example helps understand the behavior.

**Comment by BERNARDO31P** [comment]
Could you find something?

**Comment by regosen** [comment]
Hi, no I couldn't.  Here's what you can do to make issues easier to track for me: create a separate GitHub issue for each bug.  This issue is called "returning success or error when adding a track with addTrack()", so it's confusing to me what actual issues are outstanding. 

When you do create a new ticket, could you also output the console log with logLevel set to LogLevel.Debug?  That will help me investigate this further.  Thanks!
